version: 2
updates:
  - package-ecosystem: npm
    directory: /
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - javascript
    schedule:
      interval: weekly
      day: thursday
      time: '08:00'
      timezone: America/Los_Angeles
    reviewers:
      - shgysk8zer0
    assignees:
      - shgysk8zer0
  - package-ecosystem: github-actions
    directory: /
    open-pull-requests-limit: 10
    schedule:
      interval: weekly
      day: thursday
      time: '08:00'
      timezone: America/Los_Angeles
    reviewers:
      - shgysk8zer0
    assignees:
      - shgysk8zer0
